version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
