// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package dm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgTypeModelUpRaw-0]
	_ = x[MsgTypeEventPropertyPost-1]
	_ = x[MsgTypeEventPost-2]
	_ = x[MsgTypeEventPropertyPackPost-3]
	_ = x[MsgTypeDesiredPropertyGet-4]
	_ = x[MsgTypeDesiredPropertyDelete-5]
	_ = x[MsgTypeDeviceInfoUpdate-6]
	_ = x[MsgTypeDeviceInfoDelete-7]
	_ = x[MsgTypeDsltemplateGet-8]
	_ = x[MsgTypeDynamictslGet-9]
	_ = x[MsgTypeExtNtpRequest-10]
	_ = x[MsgTypeConfigGet-11]
	_ = x[MsgTypeTopoAdd-12]
	_ = x[MsgTypeTopoDelete-13]
	_ = x[MsgTypeTopoGet-14]
	_ = x[MsgTypeDevListFound-15]
	_ = x[MsgTypeSubDevRegister-16]
	_ = x[MsgTypeSubDevLogin-17]
	_ = x[MsgTypeSubDevLogout-18]
	_ = x[MsgTypeSubDevDeleteTopo-19]
	_ = x[MsgTypeQueryFOTAData-20]
	_ = x[MsgTypeQueryCOTAData-21]
	_ = x[MsgTypeRequestCOTA-22]
	_ = x[MsgTypeRequestFOTAImage-23]
	_ = x[MsgTypeReportSubDevFirmwareVersion-24]
}

const _MsgType_name = "MsgTypeModelUpRawMsgTypeEventPropertyPostMsgTypeEventPostMsgTypeEventPropertyPackPostMsgTypeDesiredPropertyGetMsgTypeDesiredPropertyDeleteMsgTypeDeviceInfoUpdateMsgTypeDeviceInfoDeleteMsgTypeDsltemplateGetMsgTypeDynamictslGetMsgTypeExtNtpRequestMsgTypeConfigGetMsgTypeTopoAddMsgTypeTopoDeleteMsgTypeTopoGetMsgTypeDevListFoundMsgTypeSubDevRegisterMsgTypeSubDevLoginMsgTypeSubDevLogoutMsgTypeSubDevDeleteTopoMsgTypeQueryFOTADataMsgTypeQueryCOTADataMsgTypeRequestCOTAMsgTypeRequestFOTAImageMsgTypeReportSubDevFirmwareVersion"

var _MsgType_index = [...]uint16{0, 17, 41, 57, 85, 110, 138, 161, 184, 205, 225, 245, 261, 275, 292, 306, 325, 346, 364, 383, 406, 426, 446, 464, 487, 521}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
