name: Go
on: [push]
jobs:
  build:
    name: Build on GO ${{matrix.go-version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.11.x", "1.12.x", "1.13.x", "1.14.x"]

    steps:
    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{matrix.go-version}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Go test
      run: go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic ./...