name: Go
on: [push]
jobs:
  build:
    name: Build on GO ${{matrix.go-version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go-version: ["1.15.x", "1.16.x"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Set up Go ${{matrix.go-version}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go-version}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Go test osx linux
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: |
        go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Go test windows
      if: matrix.os == 'windows-latest'
      run: |
        go test -v -covermode=atomic ./...